@startuml

skinparam nodesep 80

class "End Node TD" as ssat << (D, orchid) Thing Description >>

class "Generic Application" as abtm  << (M, cyan) Thing Model, Protocol-agnostic >>

class "Application" as atm << (M, cyan) Thing Model >>

class "Generic Embedded Core" as rbtm << (M, cyan) Thing Model, Protocol-agnostic >>

class "Embedded Core" as rtm << (M, cyan) Thing Model >>

class "Platform" as ptm << (M, cyan) Thing Model >>

class "Edge Connector" as ectm << (M, cyan) Thing Model >>

ssat ..|> atm : instantiated\nfrom
atm "0..*"..> "0..1" abtm : extends

atm "0..*" -right--* "1" ptm : extends /\nsubmodels
atm "0..*" -left--* "1" rtm : extends /\nsubmodels

rtm "0..*" ..> "0..1"rbtm : extends

rtm "0..*" -left..> "1" ectm : Controlled By

hide empty members

@enduml
