@startuml
left to right direction

skinparam linetype ortho
skinparam nodesep 30

() HTTP
() "Communication Protocol" as iotProt

node "SSA Edge Node" as edgeNode {
    () "IoT Network Interface" as nodeNet

    [SSA IoT Connector] as con
    [WoT Servient] as servient

    con -u- nodeNet
    con -r- servient

    servient -d..> HTTP : expose managed things
}

node "IoT Device" {
    () "IoT Network Interface" as iotNet

    frame "SSA Runtime" as ssaRuntime {
        [SSA API] as ssaApi
        [User Application] as userApp

        userApp -left..> ssaApi : use
        ssaApi -d- iotNet
    }

    [hardware drivers] as hwd
    ssaRuntime -d- hwd
}

nodeNet -up.. iotProt: use
iotNet -down.. iotProt: use

note as N
    Both the SSA Iot Connector
    and SSA Runtime instances
    must be compatible.
    That is, they must support
    the same communication
    protocol and network.
end note

N -r- iotProt

@enduml

