@startuml
left to right direction

skinparam nodesep 100

() HTTP
() "Service Protocol" as servProt
() "Connector Protocol" as conProt

node "SSA Edge Node" as edgeNode {
    [SSA IoT Connector] as iotCon
    [WoT Servient] as servient

    iotCon -l-> servient: register device
}

node "IoT Device" as device {
    [SSA Firmware] as ssaFW
    [User Application] as userApp

    [Hardware Drivers] as hwd
    [Sensors / Actuators] as hw

    hwd -d- hw
    ssaFW -l- hwd : uses
    ssaFW -d-> userApp: runs
    userApp -u-> ssaFW: uses
}

servient -u. HTTP : expose thing(s)
iotCon -d. conProt : configure device
iotCon -d. conProt : upload user code
ssaFW -u. conProt : receive updates
ssaFW -u. conProt : register in network
ssaFW -u. servProt: provide services

conProt -r[hidden]. servProt

note as N
    Connector and Service Protocol
    represent IoT communication
    tecnhologies and may be the same.
    - MQTT, CoAP, LoRaWAN, etc
end note

N -l[hidden]. servProt
N -l[hidden]. conProt

@enduml

