@startuml

left to right direction
skinparam nodesep 100

() " Interaction Affordances" as wotProt

database "Thing Registry" as db {
    folder "Thing Models" as tms
    folder "Thing Descriptions" as tds
}

database "App Registry" as appDB


node "SSA Edge Node" as edgeNode {

    [SSA Edge Connector] as ssaCon
    [SSA WoT Proxy] as ssaProxy
    [Thing Registry Client] as tRClient

    ssaCon -u-> ssaProxy : update state
    ssaProxy -d-> ssaCon : forward requests

    ssaCon -u-> tRClient : uses
    ssaCon -r-> appDB : fetch app code

}

node "SSA IoT Device" as device {
    [SSA Runtime] as ssaRt
    [User Application] as userApp

    [Hardware Drivers] as hwd
    [Sensors / Actuators] as hw

    hwd -d- hw : interfaces
    ssaRt -l-> hwd : uses
    ssaRt -d-> userApp: runs
    userApp -u-> ssaRt: uses
}

tRClient -u-> tds : register \nThing Description(s)
tRClient -u-> tms : fetch Thing Model(s)

ssaProxy -u[hidden]- tms

ssaRt -u..> ssaCon : "register, update state"
ssaCon -d..> ssaRt : "manage, update,\nforward requests"
ssaProxy -r.> wotProt : provides

@enduml
