@startuml
left to right direction

skinparam nodesep 100

() HTTP
() "SSA DB API" as db
() "WoT Affordance Protocol" as affProt
() "SSA Connector Protocol" as conProt

node "SSA Edge Node" as edgeNode {
    [SSA IoT Connector] as iotCon
    [SSA server] as server

    iotCon -l-> server
    server -> iotCon
}

node "IoT Device" as device {
    [SSA Firmware] as ssaFW
    [User Application] as userApp

    [Hardware Drivers] as hwd
    [Sensors / Actuators] as hw

    hwd -d- hw
    ssaFW -l- hwd : uses
    ssaFW -d-> userApp: runs
    userApp -u-> ssaFW: uses
}

server -u. db : fetch Thing Model(s)\nregister Thing Description(s)\nfetch User Code
server -u. HTTP : expose Thing\nDescription(s)
iotCon -d. conProt : configure device\nupload user code
ssaFW -u. conProt : receive updates\nconnect to server
ssaFW -u. affProt: provide affordances

conProt -r[hidden]. affProt

note as N
    The **SSA Connector Protocol** and the **WoT Connector**
    **Protocol** represent IoT communication tecnhologies.
    Depending on the platform, both protocols may or may
    not be implemented on top of the same communication
    stack.

    This diagram assumes that compatible implementations
    of the SSA Connector Protocol are deployed on the
    the edge node and the iot device.
end note

N -l[hidden]. affProt
N -l[hidden]. conProt

@enduml

