@startuml

left to right direction
skinparam nodesep 100

() "\t\tWoT API" as wotProt

database "Thing Registry" as db {
    folder "Thing Models" as tms {
        }

    folder "Thing Descriptions" as tds {
        }
}

database "App Registry" as appDB {
}

node "SSA Edge Node" as edgeNode {

    [SSA IoT Connector] as ssaIoT
    [SSA WoT Proxy] as ssaProxy
    [Thing Registry Client] as tRClient


    ssaIoT -u-> ssaProxy : updates
    ssaProxy -d-> ssaIoT : uses

    ssaIoT -u-> tRClient : uses
    ssaIoT -r- appDB : fetch app code

    ssaProxy -r.> wotProt : expose thing
}

node "SSA IoT Device" as device {
    [SSA Runtime] as ssaRt
    [User Application] as userApp

    [Hardware Drivers] as hwd
    [Sensors / Actuators] as hw

    hwd -d- hw
    ssaRt -l- hwd : uses
    ssaRt -d-> userApp: runs
    userApp -u-> ssaRt: uses
}

tRClient -u-> tds : register \nThing Description(s)
tRClient -u-> tms : fetch Thing Model(s)

ssaProxy -u[hidden]- tms

ssaRt -u..> ssaIoT : publish events
ssaIoT -d..> ssaRt : invoke actions\nread/write properties

@enduml
