@startuml
actor "SSA IoT Device" as Device
participant "SSA Edge Node" as Edge
database "SSA Database" as Database

Device -> Device: Boot & load configuration parameters
Device -> Device: Connect to IoT Network & SSA Edge Node
Device -> Edge: Send registration message
activate Edge

Edge -> Database: Fetch WoT Thing Model (TM) for the device
Database --> Edge: Return TM

Edge -> Database: Fetch user application code (app) based on TM
Database --> Edge: Return app

Edge -> Edge: Instantiate new WoT Thing Description (TD)
Edge --> Device: Send app

Edge -> Database: Register new TD
Edge -> Edge: Expose new TD
deactivate Edge

Device -> Device: Start operation loop\n- Listen for config/app code updates\n- Provide affordances to users
@enduml

