@startuml
!pragma teoz true
skinparam style strictuml

actor developer as dev

participant "End Node" as iotdev
participant "Edge Node" as node
database "Thing DB" as db
database "App Storage" as store

actor consumer

group init
    dev -> iotdev : flash
    dev -> iotdev : configure \n& deploy
    activate iotdev
end 

group registration
    iotdev -> node : registration
        
    activate node
    node -> node : init end-node\nregistration
    & node --> iotdev : ack
    
    activate node
    node -> db : fetch Model
    node -> store : get application code\nimplementing the Model
    
    node -> node : create TD
    deactivate node
    
    node -> iotdev : upload app\ncode
    iotdev --> node : ack
    deactivate iotdev
    
    node -> db : store TD
    & iotdev -> iotdev : run app
    activate iotdev
end

activate consumer
consumer -> node: get TD
node --> consumer: provide TD
deactivate node

loop : normal operation
    consumer -> iotdev : API request
    iotdev --> consumer : response
end loop

deactivate iotdev
deactivate consumer

@enduml
