@startuml
skinparam linetype ortho
hide empty members

abstract EdgeConnector {
    # controllerFactories: EndNodeControllerFactory[]
    # controllers: Map<string, EndNodeController>

    + abstract startRegistrationListener(): Promise<void>
    + abstract stopRegistrationListener(): Promise<void>

    + registerControllerFactory(factory: EndNodeControllerFactory)
    + getRegisteredNodes(): EndNode[]
}

interface EndNodeControllerFactory {
    + compatible: ControllerCompatibleTM
    + produce(node: EndNode) : Promise<EndNodeController>
}

interface EndNodeController{
    - endNode: EndNode
    - compatible: ControllerCompatibleTM

    + start(): void | Promise<void>
    + stop(): void | Promise<void>
    + startAdaptation(tm: ThingModel | URL): Promise<void>;
}

class EndNode{
    + uuid: string
    + manifest: Manifest
    + td: ThingDescription
    + compatible: ControllerCompatibleTM

    + static from(tm: ThingModel | URL): Promise<EndNode>
}

EndNodeController --* EndNode : contains
EndNodeControllerFactory --> EndNodeController : produces
EdgeConnector "1" --* "0..*" EndNodeController : contains
EdgeConnector "1" --* "1..*" EndNodeControllerFactory : contains

@enduml
