@startuml
skinparam linetype ortho
hide members

package "@citylink-edgenode/core" {

abstract EdgeConnector {
    # controllerFactories: EndNodeControllerFactory[]
    # controllers: Map<string, EndNodeController>

    + abstract startRegistrationListener(): Promise<void>
    + abstract stopRegistrationListener(): Promise<void>

    + registerControllerFactory(factory: EndNodeControllerFactory)
    + getRegisteredNodes(): EndNode[]
}

interface EndNodeControllerFactory {
    + compatible: ControllerCompatibleTM
    + produce(node: EndNode) : Promise<EndNodeController>
}

interface EndNodeController{
    - endNode: EndNode
    - compatible: ControllerCompatibleTM

    + start(): void | Promise<void>
    + stop(): void | Promise<void>
    + startAdaptation(tm: ThingModel | URL): Promise<void>
}

class EndNode{
    + uuid: string
    + manifest: Manifest
    + td: ThingDescription
    + compatible: ControllerCompatibleTM

    + static from(tm: ThingModel | URL): Promise<EndNode>
}

EndNodeController --* EndNode
EndNodeControllerFactory --> EndNodeController
EdgeConnector "1" --* "0..*\t   " EndNodeController
EdgeConnector "1" --* "1..*\t   " EndNodeControllerFactory

}

package "@citylink-edgenode/connector-mqtt"{
    class MQTTEdgeConnector{
        + override startRegistrationListener(): Promise<void>
        + override stopRegistrationListener(): Promise<void>
    }
}

package "@citylink-edgenode/controller-umqtt-core"{
  
    class UMQTTCoreControllerFactory {
        + compatible: ControllerCompatibleTM

        + produce(node: EndNode) : Promise<EndNodeController>
    }

    class UMQTTCoreController {
        - endNode: EndNode
        - compatible: ControllerCompatibleTM

        + start(): void | Promise<void>
        + stop(): void | Promise<void>
        + startAdaptation(tm: ThingModel | URL): Promise<void>
    }


    UMQTTCoreControllerFactory --> UMQTTCoreController
}

EdgeConnector -r--|> MQTTEdgeConnector
EndNodeControllerFactory -r..|> UMQTTCoreControllerFactory
EndNodeController -r..|> UMQTTCoreController
UMQTTCoreController --* EndNode
@enduml
