@startuml
!pragma teoz true
skinparam style strictuml

actor consumer

participant "End Node" as iotdev
participant "Edge Node" as node
database "Thing DB" as db
database "App Storage" as store

activate consumer
consumer -> node : end node adaptation\nrequest

activate node
    
    node -> db : get new TM
    node -> store : get new application

    node -> node : update end\nnode TD

    node -> iotdev : upload app
    activate iotdev
        iotdev --> node : ack
        iotdev -> iotdev : run new app
    deactivate iotdev

return provide updated TD
@enduml 
