@startuml
!pragma teoz true
skinparam style strictuml

actor developer as dev

participant "End Node" as endNode
participant "Edge Node" as edgeNode
database "WoT Repository" as db
database "File Storage" as store

actor consumer

== Pre-Operational Phases ==

group pre-configuration
    dev -> endNode : flash w/ EmbeddedCore
    dev -> endNode : configure & deploy
    activate endNode
end 

group registration
    endNode -> edgeNode : AppManifest URI
       
    activate edgeNode
    edgeNode -> edgeNode : init end-edgeNode\nregistration
    & edgeNode --> endNode : ack
    
    activate edgeNode
    edgeNode -> db : fetch Model
    edgeNode -> store : get application code\nimplementing the Model
    
    edgeNode -> edgeNode : create TD
    deactivate edgeNode
    
    edgeNode -> endNode : upload app\ncode
    endNode --> edgeNode : ack
    deactivate endNode
    
    edgeNode -> db : store TD
    & endNode -> endNode : run app
    activate endNode
end

== Operational Phases == 

activate consumer
consumer -> edgeNode: get TD
edgeNode --> consumer: provide TD
deactivate edgeNode

loop : normal operation
    consumer -> endNode : API request
    endNode --> consumer : response
end loop

deactivate endNode
deactivate consumer

@enduml
